baseURL = "https://howieyuen.github.io/"
languageCode = 'en-us'
title = "袁昊的学习笔记"
disablePathToLower = true
enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/howieyuen/hugo-book'

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[languages.en]
languageName = "English"
contentDir = "content"
weight = 1

[[menu.after]]
name = "Github"
url = "https://github.com/howieyuen/"
weight = 10

[params]
BookTheme = "light"
BookToC = true
BookLogo = "/logo.jpeg"
BookSection = "docs"
BookRepo = "https://github.com/howieyuen/howieyuen.github.io"
BookDateFormat = "January 2, 2006"
BookSearch = true
BookComments = true
BookPortableLinks = true
BookServiceWorker = true
enableGitalk = true

[params.Gitalk]
clientID = "25d476132e0758875147"
clientSecret = "024da24d24ebb684b7ea4c0d493ff531ad5a0c61"
repo = "howieyuen.github.io"
owner = "howieyuen"
admin = "howieyuen"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = false
distractionFreeMode = false
